export const routes = {
  home: "/",
  dashboard: "/dashboard",
  products: "/products",
  newProduct: "/Product-new",
  category: "/category",
  newCategory: "/category/new",
  updateCategory: "/category/update",
  subCategory: "/subcategory",
  newSubCategory: "/subcategory/new",
  updateSubCategory: "/subcategory/update",
  users: "/users",
  orders: "/orders",
  productReview: "/product-review",
  profile: "/profile",
  reports: "/reports",
};
